### ISSUE TITLE
`hyperglot` inserts Japanese in the list of languages with Latin script. The fonts with old Greek hieroglyphs are not detected. 

### ISSUE THREAD

**Issue by gusbemacbe** [rosettatype/hyperglot#109]
Good morning!

I was building a Python script that gets all my favourite languages from my YAML file and checks if one font supports these specific languages, then generates a Markdown file with a list of supported languages. 

The font “Aussan” does not have Japanese script. 

It checked that Japanese is in the list of languages with Latin script and inserted it in the list. 

I also tested another font with Japanese script (“Unifont”) and it didn't detect the Japanese language. 

* `languages.yml`:

  ```yaml
  - "por": 'Alemão'
    "eng": 'German'
    "iso": 'deu'
  - "por": 'Grego'
    "eng": 'Greek'
    "iso": 'ell'
  - "por": 'Inglês'
    "eng": 'English'
    "iso": 'eng'
  - "por": 'Português'
    "eng": 'Portuguese'
    "iso": 'por'
  - "por": 'Japonês'
    "eng": 'Japanese'
    "iso": 'jpn'
  ```

* `generate-language-support-list.py`:

  ```python
  #!/usr/bin/env python

  import json
  import os
  import yaml

  from hyperglot.parse import parse_font_chars
  from hyperglot.languages import Languages

  languages = yaml.load(open('languages.yml'), Loader=yaml.FullLoader)

  # Font name
  font = "Código aberto – Arsenal – Assuan.ttf"
  name = "Arsenal – Assuan"

  # Finding all folders until finding the font file name "unifont.ttf"
  def find_font_file(path):
      for root, dirs, files in os.walk(path):
          for file in files:
              if file == font:
                  return os.path.join(root, file)

  def test_languages():
      # Path to the font file
      font_file = find_font_file('.')

      # Parsing the font file
      chars = parse_font_chars(font_file)

      Langs = Languages()
      supported = Langs.supported(chars)

      # Writing a Markdown file
      with open('{}.md'.format(name), 'w') as f:
          f.write('#### {}\n\n' .format(name))

          f.write('* Idiomas com alfabeto latino:\n')
          for lang in languages:
            if lang["iso"] in supported["Latin"]:
              f.write("\t* {}\n".format(lang["por"]))

        # If the font does not have Greek script
        if "Greek" not in supported:
          f.write("")
        else:
          f.write('\n* Idiomas com alfabeto grego:\n')
          for lang in languages:
            if lang["iso"] in supported["Greek"]:
              f.write("\t* {}\n".format(lang["por"]))

        # If the font does not have Japanese script
        if "Japanese" not in supported:
          f.write("")
        else:
          f.write('\n* Idiomas com ideogramas japoneses:\n')
          for lang in languages:
            if lang["iso"] in supported["Japanese"]:
              f.write("\t* {}\n".format(lang["por"]))

  if __name__ == '__main__':
      test_languages()
  ```

Output:

```md
#### Arsenal – Assuan

* Idiomas com alfabeto latino:
	* Alemão
	* Inglês
	* Português
	* Japonês
```
