### ISSUE TITLE
Add Squamish (squ) + research documentation

### ISSUE THREAD

**Issue by justinpenner** [rosettatype/hyperglot#172]
Here's a preliminary entry for the [Squamish language](https://en.wikipedia.org/wiki/Squamish_language). This is my first language submission to Hyperglot, and I thought it would be helpful, for myself and others, to document my process in researching it.

For some background, I don't speak Squamish, but I live in the region this indigenous language is from. Prior to my research, I already had some familiarity with the language due to it being used prominently in place names and signage. I also frequently do graphic design work for the Squamish Nation and other local clients, which often involves typesetting in this language.

## Research

I was able to find several sources: [Wikipedia](https://en.wikipedia.org/wiki/Squamish_language), [FirstVoices iOS keyboard app](https://apps.apple.com/ca/app/firstvoices-keyboards/id1066651145), Typotheque's book *[Indigenous North American Type](https://www.typotheque.com/books/indigenous-north-american-type)*, and a *[Squamish–English dictionary](https://uwapress.uw.edu/book/9780295990224/squamish-english-dictionary/)* from the indigenous collection at my local public library.

There were a number of differences in the orthographies documented by each of these sources, but each source gave me a fuller picture which helped me to decide what to do about the inconsistencies. The character sets I found were as follows:

23 common among all sources:

	7 a e h i k l m n p s t u w x y á é í ú ◌̓ ◌̱ ḵ

6 additional characters in Wikipedia:

	' o z ʔ ʼ ’

3 additional characters in Typotheque:

	o z ’

7 additional characters in Squamish–English dictionary:

	! , - . ? c ’

7 additional characters in FirstVoices:

	! ' , - . ? c

From the above, I made the following decisions:

- Keep all 23 common characters.
- Keep `c` because it is very commonly used in Squamish, therefore its omission from two sources appears to be an oversight.
- Keep Wikipedia's `ʼ U+02BC MODIFIER LETTER APOSTROPHE` in addition to the common `’ U+2019 RIGHT SINGLE QUOTATION MARK`, because right quotation mark is more commonly used due to keyboard settings, but apostrophe modifier is more semantically correct and some Apple systems map both to the same key, inserting one or the other based on context. Also keep `' U+0027 APOSTROPHE` as it is used instead of right quote in some keyboard layouts.
- Omit `o z` as I have yet to see any loanwords or uncommon orthographical preferences that make use of these letters, so it seems like Wikipedia may have included it erroneously, and Wikipedia was likely Typotheque's source for including it. These letters cannot even be typed in the FirstVoices keyboard, further evidence that they are not required. If new evidence arises in the future they could be added to `auxiliary` or even an alternate orthography.
- Omit `ʔ` as no evidence was found for its usage at all. The Squamish glottal stop was standardized as `7` in the typewriter era.
- Omit punctuation `. , - ? !` as punctuation is not in scope for Hyperglot (yet).
- Add uppercase forms for all letters, as they are used in Squamish similarly to English.
- Added a `design_requirement` based on a preference I've observed (but not confirmed). I suspect this preference is linked to the norms seen in fonts that support IPA, and it therefore might be a preference among many indigenous North American languages.
- Added a `note` linking back to this research.

## Result (squ.yaml)

```yaml
name: Squamish
orthographies:
- autonym: Sḵwx̱wú7mesh sníchim
  base: A Á C E É H I Í K Ḵ L M N P S T U Ú W X Y a á c e é h i í k ḵ l m n p s t u ú w x y 7 ʼ ’ ''
  marks: ◌̓ ◌̱ ◌́
  script: Latin
  status: primary
  design_requirements: Curly comma accents and right quotes are preferred (used on consonants), to differentiate from acute accents (used on vowels).
source:
- Wikipedia
- Indigenous North American Type (2023), Typotheque
- Squamish-English Dictionary (2011), Peter Jacobs and Damara Jacobs
- FirstVoices iOS keyboard
speakers: 1
speakers_date: 2014
status: living
validity: preliminary
note: Research documented at https://github.com/rosettatype/hyperglot/issues/172
```

Have I missed anything or made any errors in relation to Hyperglot or the Squamish language? I’ll leave this issue open for a bit in case anyone has feedback, then I will submit a pull request.

**Comment by kontur** [comment]
Super, thanks @justinpenner, this is very valuable! Both to have your approach documented, and to include such a very local language.

All in all this looks already very good. You can also open a PR and we refine in the PR; it's often easier to comment or amend code in the PR interface.

A few pointers:
- I think your deductions regarding the different corpus data makes sense; if something seems like it _might_ be used it can always be listed in `auxiliary` but even those only so if there is evidence of actual use.
- apostrophe vs right quote vs single quote vs comma accent is exactly #82 — for some languages there is a clear letter in use, for others there is a canonical encoding but many are used, and for others any of a number of alternatives go. My preference would be to use the most canonical (if one exists) in the `base` and add "alternates" to `auxiliary` as composed letters (for marks) or standalone letters (for characters) and make a note about this like you have done.
- The `hyperglot-save` command will automatically extract marks used in the `base` (and `auxiliary`) and adds them. This also means marks that are listed but not encountered in `base` will be implicitly required. When there are alternative ways of adding the "accent" with different marks, it is good to list to alternates in the `marks` explicitly like you have done, so they will be required when those are commonly encountered with writing the language. Note, though, that those `marks` will be _required_ for a font to support the language. If you feel some of those base + mark combinations are less used alternative spellings you could also omit the mark from the `marks` and add the combinations with that mark as `auxiliary`, which will make _those_ marks only required if checking with `--support=auxiliary`. Super tiny difference, though, and in this case I think having all the mark variations required by listing them in `marks` explicitly makes sense.
- There is an unresolved issue #116 about digraphs... for now maybe you could add them as a note, so once we somehow make their input possible we can add them easily. (now `hyperglot-save` will split digraphs into their letters, which isn't ideal in terms of preserving and representing the orthography, even if it technically covers the required characters)
- Feel free to add `punctuation: . , - ? !` — it's good to have some data for when we add the attribute (working on that); is the language explicitly not using `: ;`, for example? Is `-` really used, e.g. for hyphenating words?
- Interesting to have a numeral in the `base`!
- `note: Research documented at https://github.com/rosettatype/hyperglot/issues/172` 👍  (you can make `note:` a list like the sources, if there have several.
- I'd maybe add a note about the speaker count being `1` — I first suspected this was an input error until I looked up the language.
- When making a PR add yourself to the contributors :)

**Comment by justinpenner** [comment]
@kontur thanks, I've made a couple edits and submitted a PR (#173). Sadly the speaker count was indeed only 1 person in 2014, but happily, I found a new source (Canada's 2021 census) stating there are now 25 native speakers! I updated Wikipedia, too.

Can we already include digraphs and trigraphs in `base`, though? There are already some languages (bkm, lam, xav, tlh, esu) that have them listed, and I haven't found any problems caused by this.

**Comment by kontur** [comment]
> Can we already include digraphs and trigraphs in base, though? There are already some languages (bkm, lam, xav, tlh, esu) that have them listed, and I haven't found any problems caused by this.

Sorry, yes, include away! I misremembered, we have already changed that the input doesn't "vanish" those away on saving!

**Comment by moyogo** [comment]
It would be useful to have the graphemes using combining marks, like m̓ n̓ l̓ x̱, no? Designers may not be aware those are used and should be handled to support Squamish.

**Comment by justinpenner** [comment]
@moyogo Yes, I will add those to the PR as well. Earlier I thought that the Hyperglot database was only cataloguing individual characters, but apparently base+mark pairs and multigraphs are allowed, and should be included.

**Comment by justinpenner** [comment]
The pull request #173 now includes base+mark pairs and multigraphs:

```yaml
  base: A AA AW AW̓ AY AY̓ Á CH CHʼ E EY EY̓ EW EW̓ É H I II IW IW̓ Í K Kʼ KW KWʼ Ḵ Ḵʼ ḴW ḴWʼ L L̓ LH M M̓ N N̓ P Pʼ S SH T Tʼ TLʼ TS TSʼ U UU UY UY̓ Ú W W̓ XW X̱ X̱W Y Y̓ a aa aw aw̓ ay ay̓ á ch chʼ e ey ey̓ ew ew̓ é h i ii iw iw̓ í k kʼ kw kwʼ ḵ ḵʼ ḵw ḵwʼ l l̓ lh m m̓ n n̓ p pʼ s sh t tʼ tlʼ ts tsʼ u uu uy uy̓ ú w w̓ xw x̱ x̱w y y̓ 7 ʼ ’ ''
  marks: ◌̓ ◌̱
  punctuation: . , - ? !
```

These are all listed in a pronunciation guide section at the beginning of the Squamish–English dictionary, which seems to be more complete than the orthography listed on Wikipedia.

I used `ʼ U+02BC MODIFIER LETTER APOSTROPHE` rather than `’ U+2019 RIGHT SINGLE QUOTATION MARK` in the digraphs. It isn't standardized so either is acceptable in everyday use of the language, but apostrophe modifier is more semantically correct, I think.
