### ISSUE TITLE
Notation for inline auxiliary for any kind of character set

### ISSUE THREAD

**Issue by MrBrezina** [rosettatype/hyperglot#177]
There are situations when we want to list auxiliary characters for other kinds of things (e.g. punctuation, numerals), perhaps it would be better to have an inline notation for optional/auxiliary characters that could be used in any list of characters.

Instead of:

```
base: a b c
auxiliary: x y z
```

we could have the following (or use different escape character):

```
base: a b c \x \y \z
```

**Comment by kontur** [comment]
I'm torn on this one. In a way the base vs auxiliary is a very binary distinction, and as you mention, it could be extended to more than just the characters of base. However, adding more implicit notation seems like it will be less clear and less simple to author.

That said, this would be pretty neat. What if any auxiliary chars would be in parenthesis (I think that's not interfering with yaml parsing, but would need custom parsing all yaml strings)?:

```
name: English
orthographies:
- autonym: English
  characters: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Æ Œ a b c d e f g h i j k l m n o p q r s t u v w x y z æ œ (À Á Ç È É Ê Ë Ï Ñ Ô Ö à á ç è é ê ë ï ñ ô ö)
  currency: $ ¢ £ € (¥)
  marks: (◌̀ ◌́ ◌̂ ◌̃ ◌̈ ◌̧)
  numerals: 0 1 2 3 4 5 6 7 8 9
  punctuation: '. , ; : ? ! “ ” ‘ ’' (% & ¿ ¡)
```

Food for thought.

Also, I wonder if "extended" makes more sense as a term in the docs and CLI parameters. Like checking for basic language support vs checking for extended language support.
