### ISSUE TITLE
Update to Tamil from Aadarsh Rajan

### ISSUE THREAD

**Issue by MrBrezina** [rosettatype/hyperglot#58]
- ஃ: While the aytham has been used in grammar text as a vowel sound, now it is commonly used as a mark to indicate sounds not native to the Tamil language. The most popular one being the sound (fa) in words such as 'finance' (ஃபைனான்ஸ்)
- conjunct letters: The letters க்ஷ (kssa) ஸ்ரீ (shree) are conuncts that appear very frequently and should be acknowledged as separate from other conjunct matra forms. The க்ஷ (kssa) is a grantha character like ஜ (ja) ஶ (sha) ஷ (ssa) ஸ (sa) ஹ (ha) and is used for Sanskritised text or loan words. ஸ்ரீ (shree) is used in religious contexts or as a honorific title (eg. Shree Ashok Banerjee).
- precomposed sign (matra) forms: Changed the semantics of this statement. I want to distinguish between letter conjuncts and combined matra forms as separate concepts.
- ஃ ஂ ொ ோ ௌ: included these signs that were a part of the unicode chart.
- numerals (tamil) (latin): differentiated the two. The Tamil numerals are not in frequent use today, the Latin numerals are.
- ௦: Added the Tamil numeral zero.
- symbols (unicode): These are necessary symbols for a unicode compliant typeface. Note, ௐ (om) is categorised as a sign on the unicode guidelines.
- auxiliary (Tamil supplement): New additions to the unicode block of supplemental Tamil characters.
- references: Added links to two unicode sheets.

```
 name: Tamil
  orthographies:
  - autonym: தமிழ்
    base: அ ஆ இ ஈ உ ஊ எ ஏ ஐ ஒ ஓ ஔ ஃ க ங ச ஞ ட ண த ந ப ம ய ர ல வ ழ ள ற ன ஜ ஶ ஷ ஸ ஹ
    conjunct letters: க்ஷ ஸ்ரீ 
    design_requirements:
    - Mark positioning and precomposed sign (matra) forms are required for proper representation of the language.
    marks: ஃ ◌் ஂ ா ◌ி ◌ீ ◌ு ◌ூ ◌ெ ◌ே ◌ை ொ ோ ௌ ◌ௗ
    numerals (Tamil): ௦ ௧ ௨ ௩ ௪ ௫ ௬ ௭ ௮ ௯ ௰ ௱ ௲ 
    numerals (Latin): 0 1 2 3 4 5 6 7 8 9
    symbols (unicode): ௐ ௳ ௴ ௵ ௶ ௷ ௸ ௹ ௺
     auxiliary (Tamil supplement): 𑿀 𑿁 𑿂 𑿃 𑿄 𑿅 𑿆 𑿇 𑿈 𑿉 𑿊 𑿋 𑿌 𑿍 𑿎 𑿏 𑿐 𑿑 𑿒 𑿓 𑿔 𑿕 𑿖 𑿗 𑿘 𑿙 𑿚 𑿛 𑿜 𑿝 𑿞 𑿟 𑿠 𑿡 𑿢 𑿣 𑿤 𑿥 𑿦 𑿧 𑿨 𑿩 𑿪 𑿫 𑿬 𑿭 𑿮 𑿯 𑿰 𑿱 𑿿
    script: Tamil
    status: primary
  source:
  - Omniglot
  - Wikipedia
  - Unicode (for basic unicode compliance): https://unicode.org/charts/PDF/U0B80.pdf 
  - Unicode (for supplement): https://unicode.org/charts/PDF/U11FC0.pdf
  speakers: 75000000
  speakers_date: 2011-2015
  validity: preliminary
```
