### ISSUE TITLE
Adding Apinayé, Karo, Awetí by Rafael Dietzsch

### ISSUE THREAD

**Issue by MrBrezina** [rosettatype/hyperglot#59]
```
apn:
 name: Apinayé
 orthographies:
 - autonym:
   base: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z À Ã Ê Ô Õ à ã ê ô õ Ĩ ĩ Ũ ũ Ẽ ẽ Ỳ ỳ Ỹ ỹ
   marks:
   script: Latin
   status: primary
 source:
 speakers:
 speakers_date:
 status: living
 validity: draft


arr:
 name: Karo
 orthographies:
 - autonym:
   base: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z Ã É Í Ó Õ Ú Û á â ã é í ó õ ú û Ĩ ĩ ʼ Ẽ ẽ Ꞌ ꞌ G̃ g̃ Ã́ ã́ Ẽ́ ẽ́ Ĩ́ ĩ́ Ṍ ṍ Ấ ấ
   marks:
   script: Latin
   status: primary
 source:
 speakers:
 speakers_date:
 status: living
 validity: draft


awe:
 name: Awetí
 orthographies:
 - autonym:
   base: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z Á Ã Õ á ã õ Ĩ ĩ Ũ ũ ʼ Ẽ ẽ Ỹ ỹ Ꞌ ꞌ
   marks:
   script: Latin
   status: primary
 source:
 speakers:
 speakers_date:
 status: living
 validity: draft
```
