### ISSUE TITLE
Remove latinized autonyms for Kayah

### ISSUE THREAD

**Issue by kontur** [rosettatype/hyperglot#85]
Hey @sergiolmartins 

I saw we have two autonyms for Kayah which are written in Latin. As a base rule the autonym should be spelled in the orthography it describes.

```
...
eky:
  name: Eastern Kayah
  orthographies:
  - autonym: Kayah
    base: ꤀ ꤁ ꤂ ꤃ ꤄ ꤅ ꤆ ꤇ ꤈ ꤉ ꤊ ꤋ ꤌ ꤍ ꤎ ꤏ ꤐ ꤑ ꤒ ꤓ ꤔ ꤕ ꤖ ꤗ ꤘ ꤙ ꤚ ꤛ ꤜ ꤝ ꤞ ꤟ ꤠ ꤡ ꤢ ꤣ ꤤ ꤥ ꤮ ꤯
    marks: ◌ꤦ ◌ꤧ ◌ꤨ ◌ꤩ ◌ꤪ ◌꤫ ◌꤬ ◌꤭
    numerals: ꤀ ꤁ ꤂ ꤃ ꤄ ꤅ ꤆ ꤇ ꤈ ꤉
    script: Kayah Li
    status: primary
  source:
  - Omniglot
  - CLDR
  - Wikipedia
  status: living
  validity: preliminary
...
kyu:
  name: Western Kayah
  orthographies:
  - autonym: Karenni
    base: ꤀ ꤁ ꤂ ꤃ ꤄ ꤅ ꤆ ꤇ ꤈ ꤉ ꤊ ꤋ ꤌ ꤍ ꤎ ꤏ ꤐ ꤑ ꤒ ꤓ ꤔ ꤕ ꤖ ꤗ ꤘ ꤙ ꤚ ꤛ ꤜ ꤝ ꤞ ꤟ ꤠ ꤡ ꤢ ꤣ ꤤ ꤥ ꤮ ꤯
    marks: ◌ꤦ ◌ꤧ ◌ꤨ ◌ꤩ ◌ꤪ ◌꤫ ◌꤬ ◌꤭
    numerals: ꤀ ꤁ ꤂ ꤃ ꤄ ꤅ ꤆ ꤇ ꤈ ꤉
    script: Kayah Li
    status: primary
  source:
  - Omniglot
  - CLDR
  - Wikipedia
  status: living
  validity: preliminary
...
```

Maybe the "Karenni" vs "Kayah" terminology difference could be added as a note instead? Or we find the respective spelling in the orthographies in question.

Let me know how to proceed and I'll update the data.
