### ISSUE TITLE
Thai support

### ISSUE THREAD

**Issue by MariannaPaszkowska** [rosettatype/hyperglot#98]
Hi there, 
I noticed today that Hyperglot might not correctly recognize Thai support in fonts that fully support Thai.

I checked and had consistent behavior on four font families, including two fonts from the GF collection: Mali and Sarabun. Hyperglot doesn't show that they have any Thai in them.

**Comment by kontur** [comment]
Thanks for the report. 

@MrBrezina I've tweaked the `tha` orthography to not require these two marks `◌̍ ◌̎` as base marks, since at least none of the GF seem to require it and [Wikipedia states](https://en.wikipedia.org/wiki/Thai_script#cite_ref-vowels-1.1_19-0) that they appear only in conjunction with another combining mark (which kind of swallows them to become `U+0E35`?)

Just for future reference on how to list marks but not make them required as base — repeat them as auxiliary (`marks` is a combination of all marks, but the base/aux required ones are synthesized for the check from base, aux and marks not in either):

```
tha:
  name: Thai
  orthographies:
  - autonym: ภาษาไทย
    auxiliary: ◌̍ ◌̎
    base: ก ข ฃ ค ฅ ฆ ง จ ฉ ช ซ ฌ ญ ฎ ฏ ฐ ฑ ฒ ณ ด ต ถ ท ธ น บ ป ผ ฝ พ ฟ ภ ม ย ร ล ว ศ ษ ส ห ฬ อ ฮ ะ า เ แ โ ใ ไ ฤ ๅ ฦ ๆ
    marks: ◌̍ ◌̎ ◌ั ◌ิ ◌ุ ◌ู ◌็ ◌ํ ◌ี ◌ึ ◌ื ◌ฺ ◌่ ◌้ ◌๊ ◌๋ ◌์ ◌๎
```

@MariannaPaszkowska Those fonts should now correctly detect Thai support :)
